#!/usr/bin/env bash
# Bash3 Boilerplate. Copyright (c) 2014, kvz.io

set -o errexit
set -o pipefail
set -o nounset
############### end of Boilerplate

branch=$(/bin/git branch | awk '{print $2}')

for remote in $(/bin/git remote)
do
    /bin/git push "$remote" "$branch"
done
